from . import project_task
from . import ts_start_timesheet
from . import res_users
from . import ts_task_time_account_line
from . import account_analytic_line
from . import res_company
from . import res_config_settings
from . import create_quickly_project
from . import feedback_mailers_cron
from . import task_timer_description
from . import sale_order
from . import crm_lead